title: "Techno countdowns"
description: "Countdowns for techno festival ticket & logistics deadlines"
url: "https://epignatelli.com"         # your apex
baseurl: "/techno-deadlines.github.io" # the project path
